// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Firefox",
  handlers: [
    {
      match: /^https?:\/\/meet\.google\.com\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/sessions\.psychologytoday\.com\/.*$/,
      browser: "Safari"
    },
    {
      match: /^https?:\/\/www\.focusmate\.com\/.*$/,
      browser: "Safari"
    }
  ]
}
