# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we're using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install formulae
install z
install node
install yarn

# Remove outdated versions from the cellar
cleanup
