# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we're using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install Z for jumping around
install z

# Install NodeJS
install node

# Install everything else
install wget --enable-iri

# Remove outdated versions from the cellar
cleanup
